name: Deploy to GitHub Pages

on:
  push:
    paths:
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v2

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p public
          cp index.html public
          echo "<meta http-equiv='refresh' content='0; url=public/index.html'>" > public/index.html
          git add .
          git commit -m "page index.html]